using System;
using System.Collections.Generic;
using System.Text;

namespace Andersc.CodeLib.Common.Data
{
    public enum StatementType
    {
        // TODO: Average, Exist, Max, Min

        /// <summary>
        /// This setting is used when the statement type has not been defined or is unknown. When
        /// executing queries of unknown type, the framework assumes a select-type statement is
        /// being executed (i.e. it will use an ExecuteReader to perform the request).
        /// </summary>
        Unknown,
        /// <summary>
        /// This identifies statements executed using the ExecuteReader method.
        /// </summary>
        Select,
        /// <summary>
        /// This identifies statements executed using the ExecuteScalar method. No fields will
        /// be selected. The result set will contain a single numeric row-count value.
        /// </summary>
        Count,
        /// <summary>
        /// This identifies statements executed using the ExecuteScalar method. No fields will
        /// be selected. The result set will contain a single numeric row-count value.
        /// </summary>
        Sum,
        /// <summary>
        /// This identifies statements executed using the ExecuteScalar method. No fields will
        /// be selected. Use the LastRowId property on the SqlResult to obtain the selected value.
        /// </summary>
        Identity,
        /// <summary>
        /// This identifies statements executed using either the ExecuteScalar (for
        /// autogenerated columns) or ExecuteNonQuery method.
        /// </summary>
        Insert,
        /// <summary>
        /// This identifies statements executed using the ExecuteNonQuery method.
        /// </summary>
        Update,
        /// <summary>
        /// This identifies statements executed using the ExecuteNonQuery method.
        /// </summary>
        Delete,
        /// <summary>
        /// This identifies statements executed using the ExecuteNonQuery method.
        /// </summary>
        SoftDelete
    };
}
